### ISSUE TITLE
写缓存

### ISSUE THREAD

**Issue by yunfeiyanggzq** [HelloYym/polar-race#1]
前辈您的设计非常的出色，想问一下前辈您在keyfile里面提到的写缓存是用来做什么用的，我看了源码没有看明白，是怎么生成的，能解释下吗

**Comment by HelloYym** [comment]
直接按4KB往磁盘写数据不好，所以在内存先凑齐4个value，也就是16KB，然后再一起写到磁盘。
这个16KB的内存就是写缓存。

**Comment by yunfeiyanggzq** [comment]
您的意思是说写缓存也是放到磁盘先存着防止kill?

**Comment by yunfeiyanggzq** [comment]
我指的是图上的红色部分 https://camo.githubusercontent.com/3a0fac3267159de948a04e01f816e82c930ace69/68747470733a2f2f7773322e73696e61696d672e636e2f6c617267652f303036744e6337396c79316679746f61667263756c6a33316167306b323430372e6a7067

**Comment by HelloYym** [comment]
> 您的意思是说写缓存也是放到磁盘先存着防止kill?

对，缓存用mmap防止kill，但是缓存中的数据不一定会落盘，pagecache刷盘是由os控制的

**Comment by yunfeiyanggzq** [comment]
谢谢您
